import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";

import type { Database } from "@/lib/database.types";
import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from "@/lib/env";

/**
 * Supabase client for Server Components, Server Actions, and Route Handlers.
 *
 * Call this per request — never hoist the result into a module-level variable,
 * or one user's session leaks into another's render.
 *
 * `Database` comes from `lib/database.types.ts`, generated by the Supabase CLI.
 * Regenerate it after every migration; never hand-edit it.
 */
export async function createClient() {
  const cookieStore = await cookies();

  return createServerClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    cookies: {
      getAll() {
        return cookieStore.getAll();
      },
      setAll(cookiesToSet) {
        try {
          for (const { name, value, options } of cookiesToSet) {
            cookieStore.set(name, value, options);
          }
        } catch {
          // Server Components are not allowed to write cookies, and a refresh
          // landing mid-render throws here. Safe to swallow: proxy.ts runs on
          // every request and persists the refreshed session itself.
        }
      },
    },
  });
}
